/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vistas;

import com.gf.controles.Juego1;
import com.gf.dao.Dao;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author mario
 */
public class GUI_Juego1 extends javax.swing.JFrame {

    private static JPanel panelContenedor;
    private static Juego1 juego1;
    private static Dao dao = new Dao();

    public GUI_Juego1() {
        initComponents();
        setFrame();
//        this.dao = dao;
        this.juego1 = new Juego1(dao);
    }

    private void setFrame() {
        panelContenedor = new JPanel(new FlowLayout());
        this.setLocationRelativeTo(null);
        this.getContentPane().add(panelContenedor, BorderLayout.CENTER);
    }

    public static void insertarCuadros() throws MalformedURLException {
        JPanel panelCuadros = new JPanel(new GridLayout(2, 0));
        panelContenedor.add(panelCuadros);
        List<String> listaURLS = juego1.urlImg();
        int numeroCuadros = 10;

        for (int i = 0; i < numeroCuadros; i++) {
            JLabel cuadro = new JLabel();
            try {
                URL imagen = new URL(listaURLS.get(i));
                ImageIcon icono = new ImageIcon(imagen);
                cuadro.setIcon(icono);
            } catch (MalformedURLException e) {
                e.printStackTrace();
                throw e;
            }
            panelCuadros.add(cuadro);
        }
    }

    public static void insertarNombre() {
        JPanel panelNombres = new JPanel(new GridLayout(2, 0));
        panelContenedor.add(panelNombres);
        List<String> listaNombres = juego1.nombreObras();
        List<String> listaAutores = juego1.autoresObra(dao);
        int numeroCuadros = 10;

        for (int i = 0; i < numeroCuadros; i++) {
            String mensaje = listaNombres.get(i) + "\n" + listaAutores.get(i);
            JLabel cuadro = new JLabel(mensaje);
            panelNombres.add(cuadro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Juego1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
