/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vistas;

import com.gf.controles.Juego1;
import com.gf.dao.Dao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author mario
 */
public class GUI_Juego1 extends javax.swing.JFrame {

    private static JPanel panelContenedor = new JPanel(new GridLayout(0, 2));
    private static Juego1 juego1;
    private static Dao dao = new Dao();

    public GUI_Juego1() {
        initComponents();
        setFrame();
//        this.dao = dao;
        this.juego1 = new Juego1(dao);
        try {
            insertarCuadros();
        } catch (MalformedURLException ex) {
            Logger.getLogger(GUI_Juego1.class.getName()).log(Level.SEVERE, null, ex);
        }
        insertarNombre();
    }

    private void setFrame() {
        this.setTitle("Juego 1");
        this.setLocationRelativeTo(null);
        this.setContentPane(panelContenedor);
    }

    public static void insertarCuadros() throws MalformedURLException {
        JPanel panelCuadros = new JPanel(new GridLayout(0, 2));
        panelContenedor.add(panelCuadros);
        List<String> listaURLS = juego1.urlImg();
        int numeroCuadros = 10;

        for (int i = 0; i < numeroCuadros; i++) {
            JLabel cuadro = new JLabel();
            try {
                URL imagenUrl = new URL(listaURLS.get(i));
                ImageIcon icono = new ImageIcon(imagenUrl);
                Image imagen = icono.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                cuadro.setIcon(new ImageIcon(imagen));

            } catch (MalformedURLException e) {
                e.printStackTrace();
                throw e;
            }
            panelCuadros.add(cuadro);
        }
    }

    public static void insertarNombre() {
    JPanel panelDatos = new JPanel(new GridLayout(0, 2));
    panelContenedor.add(panelDatos);

    List<String> listaNombres = juego1.nombreObras();
    List<String> listaAutores = juego1.autoresObra(dao);
    int numeroCuadros = 10;

    for (int i = 0; i < numeroCuadros; i++) {
        String nombre = listaNombres.get(i);
        String autor = listaAutores.get(i);
        String mensaje = "<html> <h3>" + nombre + " </h3><br>" + autor + "</html>";
        JLabel datosCuadro = new JLabel(mensaje);

        Color colorNota = new Color(250, 235, 175);
        datosCuadro.setBorder(BorderFactory.createLineBorder(Color.ORANGE));
        datosCuadro.setOpaque(true);
        datosCuadro.setBackground(colorNota);

        Dimension dimension = new Dimension(200, 50);
        datosCuadro.setPreferredSize(dimension);

        datosCuadro.setHorizontalAlignment(SwingConstants.CENTER); // Centrar el texto

        panelDatos.add(datosCuadro);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Juego1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
